### PR TITLE
Add server to client config syncing Fixes #88

### LINKED ISSUE #88: Roles can't access rdm manager
I've attached the content of my config.json as a txt file.
My problem is that the roles jr.operator, operator and moderator can't access the rdm manager while the permission is set to true.

{
	"Reports": {
		"MoreReportsPerRound": false,
		"ReportsBeforePlaying": false,
		"NoStaffReports": true
	},
	"DiscordWebhookMode": 2.0,
	"PrivateMessagePrefix": "[RDM Manager]",
	"AbuseMessageMode": 0.0,
	"ForcedLanguage": "",
	"RDM_Manager_Enabled": true,
	"HideDonateButton": false,
	"Autoslay": {
		"Autoslay_CheckCustom": false,
		"DefaultReason11": "Trolling",
		"DefaultReason9": "Prop kill",
		"DefaultReason3": "2x RDM",
		"DefaultReason5": "Mass RDM",
		"DefaultReason6": "Super Mass",
		"ShowRemainingSlays": false,
		"DefaultReason10": "Consistent RDM",
		"DefaultReason8": "Hacking",
		"DefaultReason1": "Random Damage",
		"DefaultReason2": "RDM",
		"DefaultReason12": "Minge",
		"ULX_Autoslay_ForceRole": true,
		"DefaultReason": "Breaking Rules",
		"DefaultReason4": "Attempted Mass",
		"DefaultReason7": "Ghosting",
		"ULX_AutoslayMode": 1.0
	},
	"Use_MySQL": false,
	"LogDays": 61.0,
	"UseWorkshop": true,
	"Commands": {
		"RDM_Manager_Command": "!report",
		"Respond_Command": "!respond"
	},
	"Key": 99.0,
	"Permissions": {
		"founder": {
			"access_level": 4.0,
			"can_access_rdm_manager": true
		},
		"jr.operator": {
			"access_level": 3.0,
			"can_access_rdm_manager": true
		},
		"superadmin": {
			"access_level": 4.0,
			"can_access_rdm_manager": true
		},
		"owner": {
			"access_level": 4.0,
			"can_access_rdm_manager": true
		},
		"admin": {
			"access_level": 4.0,
			"can_access_rdm_manager": true
		},
		"user": {
			"access_level": 2.0,
			"can_access_rdm_manager": false
		},
		"admini": {
			"access_level": 4.0,
			"can_access_rdm_manager": true
		},
		"moderator": {
			"access_level": 3.0,
			"can_access_rdm_manager": true
		},
		"operator": {
			"access_level": 3.0,
			"can_access_rdm_manager": true
		}
	},
	"Ban": {
		"DefaultReason6": "Super Mass",
		"DefaultReason7": "Ghosting",
		"DefaultReason8": "Hacking",
		"DefaultReason11": "Random Damage",
		"DefaultReason1": "Random Damage and leave",
		"AllowBanningThruManager": true,
		"DefaultReason2": "RDM and leave",
		"DefaultReason12": "Trolling",
		"DefaultReason3": "2x RDM and leave",
		"DefaultReason10": "Attempted RDM",
		"DefaultReason4": "Attempted Mass and leave",
		"DefaultReason9": "Consistent RDM",
		"DefaultReason5": "Mass RDM"
	}
}

[config.txt](https://github.com/BadgerCode/tttdamagelogs/files/11940725/config.txt)

### PR DESCRIPTION
**Pull request by wgaylord**
A work in progress PR to fix the issue with the config not syncing to the client. 

Which I think may be why permissions aren't working properly when using the JSON config.

This is only WIP since I haven't tested it at all yet but want to show what I am doing for some feed back.

### CODE REVIEW

**Comment by wgaylord** [comment]
Did some testing and I can confirm this does fix the permission issues.

**Comment by wgaylord** [comment]
This fixes #88

**Comment by wgaylord** [comment]
Just a bump for this to get looked at.

**Comment by BadgerCode** [comment]
Looks good! I'll give it a test and add it to the next release.

Sorry for the delay

**Pull request merged**
