### PR TITLE
Add ability to see shot logs next to the damage tab

### PR DESCRIPTION
**Pull request by callumok2004**
Adds an optional feature where you can see the shot logs next to the damage tab instead of a separate page.

image

### CODE REVIEW

**Comment by BadgerCode** [comment]
Wow nice!
I'll try and give this a test sometime soon.

**Comment by callumok2004** [comment]
Hey, have you had a chance to look at this yet?

**Comment by BadgerCode** [comment]
Hey! Sorry for the lack of activity and massive delay.
My priorities have shifted, so I've been unable to work on this.

However, I will accept your pull request and look to sort out a new release of this!

**Comment by wgaylord** [comment]
This PR causes errors due to missing `end` in the oldlogs.lua file.

**Comment by BadgerCode** [comment]
Ah yeah. That's my fault for not having the time to look after this.
I shall fix master and spend some time on this project tomorrow.

**Pull request merged**
